### ISSUE TITLE
"grammar helpers" similar to some "type helpers" of TypeScript

### ISSUE THREAD

**Issue by trusktr** [langium/langium#1088]
Sometimes I feel like I want to use something like TypeScript's [`Exclude`](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludeuniontype-excludedmembers) or [`Extract`](https://www.typescriptlang.org/docs/handbook/utility-types.html#extracttype-union) helpers, but for grammar.

For example, given this current grammar code:

```py
Something:
  A | B | C;

OtherThing:
  A | C;
```

if we had helpers, the same could be written like this:

```py
Something:
  A | B | C;

OtherThing:
  Exclude<Something, B>;
```

**Comment by msujew** [comment]
I agree with @spoenemann. `Exclude` works in TypeScript, because it is a structural type system. However, Langium actually implements a nominal type system through its grammar which isn't compatible with such constructs. This makes implementing the general case tricky. For example, what is the result of the following?

```
Something:
  B value=ID;

OtherThing:
  Exclude<Something, B>;
```

Would this only result in a parser rule `value=ID`? And what is its type, if not `B`? Given that grammars can be arbitrarily complex and it's not even clear what the result of some operations is supposed to be I would say this is a out of scope for Langium.

**Comment by msujew** [comment]
I don't think that this is in scope for Langium. It's unclear how this is supposed to be implemented, and it's basically just syntactic sugar for the grammar language.
