### ISSUE TITLE
Reference fails to resolve ...

### ISSUE THREAD

**Issue by Reyems** [langium/langium#1101]
Langium version: Latest

## Steps To Reproduce

1. On Playground sample, change  "Person:  'person' name=ID;" to "Person:  'person' pname=ID;" 

## The current behavior
Could not resolve reference to Person named 'John'.HelloWorld(linking-error)

## The expected behavior
resolve reference as normal regardless of variable name or pname?

**Comment by msujew** [comment]
@Reyems Given that an AST node can have completely arbitrary properties, there needs to be some convention on what is considered an objects name so that the framework can resolve cross references. This convention is using a property called `name`. This behavior is outlined [here](https://langium.org/docs/grammar-language/#cross-references).

Note that you can change the behavior for your language by overriding the [`NameProvider`](https://github.com/langium/langium/blob/main/packages/langium/src/references/name-provider.ts).

Does that clear things up?

**Comment by Reyems** [comment]
Thanks!
