### ISSUE TITLE
Common properties are lifted into the super type regardless of their own type

### ISSUE THREAD

**Issue by msujew** [langium/langium#176]
Langium version: 0.1.0
Package name: `langium-cli`

## Steps To Reproduce

1. Create a grammar like this:
```
Token: TokenA | TokenB;
TokenA: name=('A1' | 'A2');
TokenB: name=('B1' | 'B2' | 'B3');
```
2. Generate the AST and see that the `Token` type contains a single property `name: 'A'`.

## The current behavior

The `name` property is not put into consideration when lifting fields.

## The expected behavior

Properties are not lifted, if their types aren't compatible.

**Comment by danieldietrich** [comment]
If `tokenA: name='A'` and `tokenB: name='B'`, then `token` would contain the common property `name: 'A' | 'B'`, right?

(Disclaimer: I am on a mobile phone, no way to test it)

**Comment by Pluralia** [comment]
I've updated the example.

> If tokenA: name='A' and tokenB: name='B', then the token type would contain the common property name: 'A' | 'B', right?
Now the `Token` contains the common property `name`, but its type is `'A1' | 'A2'` (or `'B1' | 'B2' | 'B3'` -- depends on which rule is defined the first). It's wrong, because we lose information about `TokenB`'s name property.

Possible solutions:
1. Don't lift `name` property, because `TokenA` and `TokenB` have different types for this property.
2. Make the `Token` `name` property type as `'A1' | 'A2' | 'B1' | 'B2' | 'B3'` [I think, the 1st option is better, because 2nd one generalises types too much].

**Comment by msujew** [comment]
> then the token type would contain the common property name: 'A' | 'B', right?

No, right now, it doesn't. Like @Pluralia said, only one of the types is lifted. I agree with her, that unless the types are exactly the same, properties shouldn't be lifted to preserve their type information.
