### ISSUE TITLE
Widen the range of applications for Cross-References

### ISSUE THREAD

**Issue by danieldietrich** [langium/langium#356]
With the new colon ':' syntax, Cross-References already look like rules. Why not treat a Cross-Reference as "inline rules" (that return a type)?

In the case of a Cross-Reference `identifier=[type:token]` I suggest to allow rule references and inline rules in place of _token_.

**Examples:**

```js
// rule reference
Rule: func=[AbstractFunc: SomeRule] ;
SomeRule: ... ;

// rule alternatives
Rule: func=[AbstractFunc: Rule1 | Rule2] ;
Rule1: ... ;
Rule2: ... ;

// token
Rule: func=[AbstractFunc: TOKEN] ;
TOKEN: ... ;
```

**Question / offtopic:** Would it make sense to allow named references (here: `SomeRule.name`)?

```js
// rule reference
Rule: func=[AbstractFunc: SomeRule.name] ; // SomeRule.name evaluates to ID
SomeRule: name=ID ;
```

**Comment by spoenemann** [comment]
> I suggest to allow rule references

That's already possible. But we restrict this to _data type rules_, i.e. parser rules that evaluate to a single primitive value (usually a string) instead of an object. IMO using an object-typed rule wouldn't make sense, as here we're interested only in the the _name_ of our reference target, not its full definition (which may be arbitrarily complex with many nested objects).

> and inline rules

We already have a form of "inline rules": [Actions](https://langium.org/docs/grammar-language/#simple-actions). But again, we only look at how to parse the name of our reference target, not the whole object subtree. I don't see much benefit in declaring a data type rule inline, but I may be convinced with an example showing how it can improve readability or other aspects of the grammar.

> Would it make sense to allow named references

In principle, yes. Our default behavior is to resolve the `name` property of our reference target. However, the way how we currently offer to customize that is through the [NameProvider](https://github.com/langium/langium/blob/main/packages/langium/src/references/name-provider.ts) service, so we offer maximum flexibility to compute the name from other properties. It would be hard to capture the same flexibility in the grammar language itself.

I propose to close this issue and reopen in case we want to revive the ideas of widening the cross-reference syntax.
