### ISSUE TITLE
Switch from colors to chalk

### ISSUE THREAD

**Issue by spoenemann** [langium/langium#574]
The [colors](https://www.npmjs.com/package/colors) package is subject to a [vulnerability](https://security.snyk.io/vuln/SNYK-JS-COLORS-2331906). We should switch to [chalk](https://www.npmjs.com/package/chalk), which is already used by the Yeoman generator.

This affects `langium-cli`, the example CLIs, and the Yeoman template project.

**Comment by snarkipus** [comment]
Since it's marked 'good first issue' I thought 'why not' ... so I forked it and took a whack ([here](https://github.com/snarkipus/langium))

I'm sort of stumbling through this blindly, but the tests seem close'ish:
```term
Test Suites: 4 failed, 29 passed, 33 total
Tests:       2 failed, 350 passed, 352 total
Snapshots:   0 total
Time:        4.244 s
Ran all test suites.
```
However, I'm not sure what to make of these errors (which are obviously related to the change) ... I'm sure this is a TS/JS thing but that's outside my expertise. Before I start guessing with json files, I figured I'd see if anybody had a recommendation.
```js
FAIL  packages/langium-cli/test/generator/module-generator.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/snarkipus/Projects/langium/langium-dev/langium/node_modules/chalk/source/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import ansiStyles from '#ansi-styles';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      11 | import * as readline from 'readline';
      12 | import type { GenerateOptions } from '../generate';
    > 13 | import chalk from 'chalk';
         | ^
      14 |
      15 | //eslint-disable-next-line @typescript-eslint/no-explicit-any
      16 | export function log(level: 'log' | 'warn' | 'error', options: GenerateOptions, message: string, ...args: any[]): void {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (packages/langium-cli/src/generator/util.ts:13:1)
```

**Comment by msujew** [comment]
@snarkipus Thanks for taking a shot at this!

The issue Jest complains about here is that Chalk is packaged in the ESM format, which isn't really well supported by TypeScript. The [Readme](https://github.com/chalk/chalk#install) recommends to run with chalk 4 instead of the newest chalk 5, so we should probably stick to that. We already use chalk 4 in the [`generator-langium`](https://github.com/langium/langium/blob/8cf37ea50033f32d20a4e5c62d627b844f4df7c1/packages/generator-langium/package.json#L35) project.

**Comment by snarkipus** [comment]
Turns out reading is important ... that detail was quite literally the first line in the README after `npm install`. :)

Created a pull request (I think) ... all tests are passing now.
