### ISSUE TITLE
Exemplify unordered groups with cardinality

### ISSUE THREAD

**Issue by Roenbaeck** [langium/langium#725]
I cannot find an example in the documentation that combines unordered groups with cardinality. Therefore I cannot get the following simple grammar to work properly. 
```
grammar ER

entry Model:
    (entity+=Entity | relationship+=Relationship)*;

Entity:
    'entity' name=NAME;

Relationship:
    'relationship' (related+=[Entity:NAME] & role+=ROLE)+;

hidden terminal WS: /\s+/;
terminal NAME: /[A-Z][\w_]*/;
terminal ROLE: /[a-z][\w_]*/;
```
With the DSL example:
```
entity Customer
entity Store
entity Product

relationship Customer bought the Product in Store
```
Can you add an example showcasing this combination? An answer that gets my particular example in working order is also appreciated, of course.

**Comment by msujew** [comment]
Hey @Roenbaeck,

I'm not too sure what you plan to achieve given your grammar snippet is actually possible. How unordered groups groups work internally is by actually using alternatives (`|`) and preventing parsing alternatives which already have been parsed. In your case, this would lead to a grammar which would look similar to this: `(NAME | ROLE)+`. Since `NAME` and `ROLE` are basically the exact same terminal, the lexer will always choose the first - probably `NAME`, by order of appearance - and then always parse `related+=[Entity:NAME]`, because it never gets the `ROLE` token from the lexer.

Anyway, going more in-depth on unordered groups: I believe that our documentation is a bit outdated and unordered groups work a bit differently from what one would expect: An unordered group such as `A & B` gets rewritten internally into `(A | B)*` with the guarantee that after parsing `A` it won't try to parse `A` again. Consequently, wrapping an unordered group into another cardinality has no effect, as `((A | B)*)+` doesn't do anything compared to just `(A | B)*`.

**Comment by Roenbaeck** [comment]
I see, in this case `NAME` and `ROLE` do differ though. The first letter is a capital in a `NAME` and not in a `ROLE`. The reason I thought it would work is that the following very similar grammar works: 
```
grammar ER

entry Model:
    (entity+=Entity | relationship+=Relationship)*;

Entity:
    'entity' name=NAME;

Relationship:
    'relationship' (related+=[Entity:NAME] role+=ROLE)+;

hidden terminal WS: /\s+/;
terminal NAME: /[A-Z][\w_]*/;
terminal ROLE: /[a-z][\w_]*/;
```
With the less human readable DSL: 
```
entity Customer
entity Store
entity Product

relationship Customer bought Product the Store in
```

**Comment by msujew** [comment]
I see, I didn't notice the different case, you're right. Anyway, so what you're looking for is to be able to write an uppercase ID (`NAME`) and then a lowercase ID (`ROLE`) or in reverse, repeating. This isn't currently achievable using unordered groups. However, something like this would work:

```
Relationship:
    'relationship' (related+=[Entity:NAME] role+=ROLE | role+=ROLE related+=[Entity:NAME])+;
```

It doesn't scale too well, as every new entry in the list increases the available options factorially, but it works for 2 at least.

**Comment by msujew** [comment]
I will close this issue, since there's nothing actionable here anymore. If you have improvements to the documentation, please leave them over at [our website repo](https://github.com/langium/langium-website).
