### ISSUE TITLE
consolidating language file .extension

### ISSUE THREAD

**Issue by trusktr** [langium/langium#919]
A language's file extensions (f.e. `.foo`, `.bar`) are currently listed in at least three places:

- package.json
- langium-config.json 
- extension.ts

Can we consolidate this to one location somehow?

**Comment by msujew** [comment]
I think this feature is a bit out of scope. In the end we have one source of truth for langium (`langium-config.json`), and then some additional information for vscode (`package.json`/`extension.ts`). Since we don't want to bind ourselves to closely to vscode - keep in mind that we support the LSP, not vscode - I don't see how we can consolidate this any further.

I'll close this for now, since I don't see a good way to improve on this. We can reopen it if someone has a good solution.
